require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'bin/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
  SuggestExtensions: false

Rails:
  Enabled: true

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Exclude:
    - '**/*.rb'